# Generated by Django 2.2.4 on 2019-08-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_lessonanswer_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LessonQuestion'),
        ),
    ]
