# Generated by Django 2.2.4 on 2019-08-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190824_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontest',
            name='time',
        ),
    ]
