# Generated by Django 2.2.4 on 2019-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_lessontest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontest',
            name='test_status',
        ),
        migrations.AddField(
            model_name='lessontest',
            name='test_mark',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
