# Generated by Django 2.2.4 on 2019-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190824_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontest',
            name='test_mark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
